[package]
name = "advent"
version = "0.1.0"
authors = ["Marcus Recck <mrecck@datto.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.7.11"
regex = "1"
lazy_static = "1.4.0"